# Generated by Django 2.1.5 on 2019-01-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='user_image',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
