# Generated by Django 2.1.5 on 2019-01-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190120_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
