# Generated by Django 2.1.5 on 2019-01-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190120_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='user_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
