# Generated by Django 2.1.5 on 2019-01-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190120_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='user_image',
            field=models.ImageField(upload_to='blogimg'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_image',
            field=models.ImageField(upload_to='commentimg'),
        ),
        migrations.AlterField(
            model_name='users',
            name='head_img',
            field=models.ImageField(upload_to='headimg'),
        ),
    ]
